/**:
  ros__parameters:
    show_debug_info: false
    enable_yaw_bias_estimation: false
    predict_frequency: 40.0
    tf_rate: 40.0
    extend_state_step: 40

    # for Pose measurement
    pose_additional_delay: 0.00
    pose_measure_uncertainty_time: 0.00
    #pose_smoothing_steps: 5
    pose_smoothing_steps: 1  # 연산량 감소
    pose_gate_dist: 10000.0
    #pose_gate_dist: 1000.0

    # for twist measurement
    twist_additional_delay: 0.00
    twist_smoothing_steps: 1
    twist_gate_dist: 5000.0
    #twist_gate_dist: 1000.0

    # for process model
    proc_stddev_yaw_c: 0.05
    proc_stddev_vx_c: 3.0
    proc_stddev_wz_c: 1.0

    # for diagnostics
    pose_no_update_count_threshold_warn: 50
    pose_no_update_count_threshold_error: 250
    twist_no_update_count_threshold_warn: 50
    twist_no_update_count_threshold_error: 250

    # for velocity measurement limitation (Set 0.0 if you want to ignore)
    threshold_observable_velocity_mps: 0.0 # [m/s]
